### ISSUE TITLE
U can play with bots and cheats and got 1st rank? Rly?

### ISSUE THREAD

**Issue by exotickg1** [cowsforyou/barracks_master#1]
Look at gold. Maybe ban this faggot and fix the problem? Thanks
http://www.barracksmaster.com/players/76561198094206002
Sry for my English.

**Comment by exotickg1** [comment]
1 more player
http://www.barracksmaster.com/players/76561198103660926

I have played enough (>22) games from June, and I am sure that 75 games - it's too much. And I know that it is impossible to earn 99,999 gold.

And most importantly - I've never seen them in the game as they play. They never came across to me.

**Comment by MNoya** [comment]
Thanks for letting us know, I'll make it so that cheat-enabled lobbies give 0 points

**Comment by cowsforyou** [comment]
Hello @exotickg1 that 99,999 gold looks very suspicious indeed. Will work on getting the match history for the players out and will verify. Thanks for reporting!

**Comment by exotickg1** [comment]
Thanks!

**Comment by MNoya** [comment]
@cowsforyou will handle the website cleaning, I will push this update now

**Comment by cowsforyou** [comment]
@exotickg1 it seems that their games are legitimate. The only game where they had the cheats on was a 1v1 game when they played vs each other (probably testing things).

@MNoya has pushed the patch to ignore cheat enabled games so that won't happen again.

The website also now shows the match history: [Example](http://www.barracksmaster.com/players/76561198094206002)

If you want to see a bit more details you can also cross check with [getdotastats](https://getdotastats.com/#s2__user?id=76561198094206002).
